name: ejecucion_pruebas
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compile Java code
      run: javac -cp .:lib/* -d bin src/**/*.java test/**/*.java

    - name: Run all JUnit tests
      run: |
        TEST_CLASSES=$(find bin -name "*Test.class" | sed 's/bin\///;s/\.class//;s/\//./g')
        java -cp .:bin:lib/* org.junit.runner.JUnitCore $TEST_CLASSES
